version: '3.3'
services:
    bombsquad-server:
        #image: crazyuploader/bombsquad
        build: .
        ports:
            - '43210:43210/udp'
        container_name: bombsquad
        volumes:
            - './config.yaml:/app/bombsquad-server/config.yaml'
            - './ba_root:/app/bombsquad-server/dist/ba_root'
